import sqlite3
import os

LOG_DB_PATH = os.path.join(os.path.dirname(__file__), '../../query_logs.db')

def init_logger():
    conn = sqlite3.connect(LOG_DB_PATH)
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS logs
                 (id INTEGER PRIMARY KEY AUTOINCREMENT,
                  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                  database TEXT,
                  user_query TEXT,
                  sql_query TEXT,
                  ai_latency REAL,
                  db_latency REAL,
                  prompt_tokens INTEGER,
                  completion_tokens INTEGER,
                  complexity TEXT,
                  status TEXT)''')
    # Add new columns for cache and cost tracking
    try:
        c.execute("ALTER TABLE logs ADD COLUMN source TEXT DEFAULT 'LLM'")
        c.execute("ALTER TABLE logs ADD COLUMN cost REAL DEFAULT 0.0")
    except sqlite3.OperationalError:
        pass # Columns probably already exist
    conn.commit()
    conn.close()

def get_cached_sql(database, user_query):
    conn = sqlite3.connect(LOG_DB_PATH)
    c = conn.cursor()
    # Search for an exact text match for the same database that was successfully generated by LLM
    c.execute('SELECT sql_query, complexity FROM logs WHERE database=? AND LOWER(user_query)=LOWER(?) AND status="SUCCESS" AND sql_query != "" LIMIT 1', (database, user_query))
    row = c.fetchone()
    conn.close()
    if row:
        return {"sql_query": row[0], "complexity": row[1]}
    return None

def log_query(database, user_query, sql_query, ai_latency, db_latency, prompt_tokens, completion_tokens, complexity, status, source="LLM", cost=0.0):
    conn = sqlite3.connect(LOG_DB_PATH)
    c = conn.cursor()
    c.execute('''INSERT INTO logs (database, user_query, sql_query, ai_latency, db_latency, prompt_tokens, completion_tokens, complexity, status, source, cost)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)''', 
                 (database, user_query, sql_query, ai_latency, db_latency, prompt_tokens, completion_tokens, complexity, status, source, cost))
    conn.commit()
    conn.close()
    
def get_logs():
    conn = sqlite3.connect(LOG_DB_PATH)
    c = conn.cursor()
    c.execute('SELECT * FROM logs ORDER BY timestamp DESC LIMIT 1000')
    rows = c.fetchall()
    columns = [description[0] for description in c.description]
    conn.close()
    return [dict(zip(columns, row)) for row in rows]
